server:
  port: ${CLOUD_GATEWAY_PORT:8084}

spring:
  application:
    name: cloud-gateway
  main:
    allow-bean-definition-overriding: true
    web-application-type: reactive

  cloud:
    gateway:
      routes:
        - id: credit-service
          uri: lb://credit-service
          predicates:
            - Path=/rest/credits/**
#          filters:
#            - name: CircuitBreaker
#              args:
#                name: CREDIT-SERVICE
#                fallbackuri: forward:/creditServiceFallBack
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/rest/customers/**
#          filters:
#            - name: CircuitBreaker
#              args:
#                name: CUSTOMER-SERVICE
#                fallbackuri: forward:/customerServiceFallBack

eureka:
  instance:
    hostname: ${API_GATEWAY_HOST:localhost}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://${SERVICE_REGISTRY_HOST:localhost}:${SERVICE_REGISTRY_PORT:8761}/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

#resilience4j:
#  circuitbreaker:
#    configs:
#      default:
#        registerHealthIndicator: true
#        slidingWindowSize: 5
#        failureRateThreshold: 50
#        waitDurationInOpenState: 10s
#        permittedNumberOfCallsInHalfOpenState: 2
#  timelimiter:
#    configs:
#      default:
#        timeoutDuration: 30s
#
#management:
#  tracing:
#    sampling:
#      probability: 1.0