server:
  port: 8081

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/credits

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/${keycloak.realm}
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs


jwt:
  auth:
    converter:
      resource-id: auth-service-client
      principle-attribute: preferred_username

keycloak:
  realm: credit-service-application-realm
  domain: localhost:9090
  adminClientId: admin-cli
  adminClientSecret: JB6XOSHxrlgAALs6OQ2NEU3R19cdHm47
  client: auth-service-client
  urls:
    auth: http://${keycloak.domain}
