server:
  port: 8082

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/customers}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:123456}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${KEYCLOAK_HOST:localhost}:${KEYCLOAK_PORT:9090}/realms/${keycloak.realm}
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

keycloak:
  realm: credit-service-application-realm
  domain: ${KEYCLOAK_HOST:localhost}:${KEYCLOAK_PORT:9090}
  adminClientId: admin-cli
  adminClientSecret: JB6XOSHxrlgAALs6OQ2NEU3R19cdHm47
  client: auth-service-client
  urls:
    auth: http://${keycloak.domain}


jwt:
  auth:
    converter:
      resource-id: auth-service-client
      principle-attribute: preferred_username