eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
  instance:
    hostname: ${SERVICE_REGISTRY_HOST:localhost}

server:
  port: ${SERVICE_REGISTRY_PORT:8761}
spring:
  application:
    name: service-registry