eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
  instance:
    hostname: ${SERVICE_DISCOVERY_HOST:localhost}

server:
  port: ${SERVICE_DISCOVERY_PORT:8761}
spring:
  application:
    name: ${APPNAME_SERVICE_DISCOVERY:service-registry}